Association
ANTOINE1128/OOP--School--Library pull request #3
Opened 2023-08-03 13:41 UTC by ANTOINE1128

# in this PR I have followed these project requirements :
Create a class Classroom with the following:
@label instance variable should be initialized in the constructor.
Setter and getter for @label (remember about attr_accessor).
Create the has-many/belongs-to relationship between Classroom and Student. The following should be implemented:
Create the has-many side (a classroom has many students).
Create the belongs-to side (a student belongs to a classroom).
Make sure that when adding a student to a classroom it also sets the classroom for the student.
Make sure that when setting the classroom for a student it also adds it to the classrooms' students.
Create a class Book with the following:
@title and @author instance variables should be initialized in the constructor.
Setters and getters for instance variables (remember about attr_accessor).
Create a class Rental with the following:
@date instance variable should be initialized in the constructor.
Setter and getter for @date (remember about attr_accessor).
Create the many-to-many (also has-many-through) relationship between Person and Book using the intermediate class Rental. The following should be implemented:
Create the has-many side of Book and Rental (a book has many rentals).
Create the belongs-to side of Rental and Book (a rental belongs to a book).
Create the has-many side of Person and Rental (a person has many rentals).
Create the belongs-to side of Rental and Person (a rental belongs to a person).
Modify the constructor of Rental so Book and Person are set in it.

2023-08-03 16:26 UTC, souad988 requested changes
Hi @ANTOINE1128 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


![242722065-db428b0c-8dfc-49c4-a156-42f227e32868](https://github.com/ANTOINE1128/OOP--School--Library/assets/59707859/6dbf7aa1-3468-468b-a5ee-e0899c2e4d94)


## Highlights
Professional README
Add exemples to run code

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-03 16:26 UTC, souad988 commented on book.rb
> +  def add_rental(rental)
Good job by adding add_rental method to the book class 👍🏼  , but the optimal solution to handle this many to many relation is to create the new rental instance here in this method and in rental initializer push in rentals of book and of person this way when you call Book.add_rental all 'belongs-to' and has-many associations will be created

```ruby
def add_rental(person, date)
    # *the book itself should be sent as a parameter to create the new rental achieving the 'has-many' association. 
    Rental.new(date, self, person)
  end
```

2023-08-03 16:26 UTC, souad988 commented on person.rb
>    end
same comment as in Book add_rental goes here

2023-08-03 16:26 UTC, souad988 commented on person.rb
> +# require_relative 'student'
kindly make sure to remove all commented code to keep your code base clean

2023-08-03 16:26 UTC, souad988 commented on student.rb
> +    classroom.students.push(self) unless classroom.students.include?(self)
I would suggest creating a setter for classroom attribute as we may need to create a student before assigning a classroom 
Check for a method that serves as the 'belongs-to' side (a student belongs to a classroom). [https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/articles/oop_relationships_by_examples.md#both-ways-relationships)

````ruby
attr_reader :classroom
  def classroom=(classroom)
      @classroom = classroom
      classroom.students.push(self) unless classroom.students.include?(self)
  end
````

2023-08-04 07:49 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @ANTOINE1128 

Your project is complete! Great job for implementing the requested changes🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- classes well linked
- Methods ok
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-05 05:32 UTC, merged